name: Deploy Next.js to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Zip artifact for deployment
        run: zip -r release.zip .next public package.json node_modules next.config.js

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7FF551F2A10C468793A045E5EF27A67A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_135063EDE3B34A7AA68866CF02923448 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F9FCDB2931724A639FF143DEFFD7435E }}
          
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dinet-staging-web'
          slot-name: 'Production'
          package: release.zip
